async page=>{
 const c=await page.context().browser().newContext({viewport:{width:1280,height:900}}),p=await c.newPage(),base='http://127.0.0.1:3793';const errors=[];p.on('pageerror',e=>errors.push(e.message));const assert=(v,m)=>{if(!v)throw Error(m)};
 await p.goto(base+'/shop/');
 const receipts=await p.evaluate(async()=>{const product=(await(await fetch('/api/v1/products?limit=24')).json()).items[0],results=[];for(let n=0;n<3;n++){const key=crypto.randomUUID();const body={buyer:{fullName:'Synthetic Buyer',email:'synthetic@example.invalid',whatsappPhone:'+6581234567'},whatsappOrderContactOptIn:false,locale:'en',deliveries:[{recipient:{fullName:'Synthetic One',phone:'+60123456789'},address:{line1:'Synthetic First Address',city:'Synthetic City',region:'Selangor',postcode:'50000',country:'MY'},items:[{productId:product.id,quantity:2,expectedPriceMinor:product.priceMinor,expectedCurrency:product.currency}]},{recipient:{fullName:'Synthetic Two',phone:'+60123456789'},address:{line1:'Synthetic Second Address',city:'Synthetic City',region:'Selangor',postcode:'50000',country:'MY'},items:[{productId:product.id,quantity:3,expectedPriceMinor:product.priceMinor,expectedCurrency:product.currency}]}]};const r=await fetch('/api/v1/orders',{method:'POST',headers:{'content-type':'application/json','idempotency-key':key},body:JSON.stringify(body)});if(r.status!==201)throw Error('synthetic submit '+r.status);results.push({receipt:await r.json(),key,product})}return results});
 await p.goto(base+'/seller/');await p.locator('#username').fill('seller_qa');await p.locator('#password').fill('SyntheticSellerLocal48125');await p.locator('#login-form').evaluate(f=>f.requestSubmit());await p.locator('#workspace').waitFor({state:'visible'});await p.goto(base+'/seller/#review');await p.locator('.order-card').first().waitFor();
 const card=p.locator('.order-card').first();await card.click();await p.locator('[data-action="confirm"]').waitFor();
 const submitted=await p.locator('.order-number').textContent();await p.getByRole('button',{name:'Order summary',exact:true}).click();await p.locator('#order-document-dialog').waitFor({state:'visible'});assert((await p.locator('.order-document-page').count())===2,'two destinations');assert((await p.locator('#order-document-dialog').textContent()).includes('DEMO'),'demo disclosed');await p.keyboard.press('Escape');
 await p.locator('[data-action="confirm"]').click();await p.locator('#decision-submit').evaluate(b=>{b.click();b.click()});await p.waitForFunction(()=>document.querySelector('#order-detail-content .order-chip')?.textContent==='Confirmed');assert(await p.locator('[data-action="confirm"]').count()===0,'decision final');
 await p.getByRole('button',{name:'Packing sheet',exact:true}).click();await p.locator('#order-document-dialog').waitFor({state:'visible'});await p.screenshot({path:'output/playwright/seller-packing-local-desktop.png'});await p.keyboard.press('Escape');
 await p.locator('.order-card').first().click();await p.locator('[data-action="reject"]').click();await p.locator('#decision-reason').fill('Synthetic unavailable');await p.locator('#decision-submit').click();await p.waitForFunction(()=>document.querySelector('#order-detail-content .order-chip')?.textContent==='Rejected');
 await p.goto(base+'/seller/#orders');await p.locator('.order-card').first().waitFor();const count=await p.locator('.order-card').count();await p.route('**/api/v1/seller/orders?*',r=>r.fulfill({status:503,contentType:'application/json',body:'{"error":{"code":"UNAVAILABLE"}}'}));await p.locator('#order-filter').evaluate(f=>f.requestSubmit());await p.locator('#order-retry').waitFor({state:'visible'});assert(await p.locator('.order-card').count()===count,'cached queue retained');await p.unrouteAll({behavior:'wait'});await p.locator('#order-retry').click();await p.waitForFunction(()=>document.querySelector('#order-retry').hidden);
 const unchanged=p.locator('.order-card').last();await p.route('**/api/v1/seller/orders/*',r=>r.fulfill({status:503,contentType:'application/json',body:'{"error":{"code":"UNAVAILABLE"}}'}));await unchanged.click();await p.locator('#order-detail-content .order-retry').waitFor();await p.unrouteAll({behavior:'wait'});await p.locator('#order-detail-content .order-retry').click();await p.locator('.order-number').waitFor();
 const result=await p.evaluate(async creds=>{const r=await fetch('/api/v1/orders/statuses',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({orders:creds})});return r.json()},receipts.map(x=>({orderNo:x.receipt.orderNo,accessKey:x.key})));assert(result.items.some(x=>x.orderNo===submitted&&x.status==='CONFIRMED'),'buyer sees confirmation');assert(result.items.some(x=>x.status==='REJECTED'),'buyer sees rejection');
 for(const width of [320,375,393,430,820,1280]){await p.setViewportSize({width,height:812});await p.waitForTimeout(250);assert(!await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'seller overflow '+width);for(const locale of ['en','ms','zh-Hans','vi','th','ja','ko']){await p.evaluate(async l=>(await import('/shared/i18n.js')).setLocale(l),locale);assert(!await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),'seller localized overflow '+width+' '+locale)}}
 await p.evaluate(async()=>(await import('/shared/i18n.js')).setLocale('en'));await p.setViewportSize({width:375,height:812});await p.getByRole('button',{name:'Order summary',exact:true}).click();await p.locator('#order-document-dialog').waitFor({state:'visible'});assert(!await p.locator('#order-document-dialog').evaluate(e=>e.scrollWidth>e.clientWidth),'preview overflow');await p.screenshot({path:'output/playwright/seller-document-local-375.png'});await p.keyboard.press('Escape');
 const unauth=await c.browser().newContext();const q=await unauth.newPage();await q.goto(base+'/seller/');assert((await q.request.get(base+'/api/v1/seller/orders')).status()===401,'unauth queue');await unauth.close();assert(!errors.length,'console errors '+errors.join(','));await c.close();return{passed:'isolated 3 buyer submits, authenticated review confirm/reject, no double decision, buyer status feedback, two-destination demo docs, cached queue error/retry, detail retry, six widths/seven locales, unauthorized denial',writes:'synthetic local DB only'};
}
