import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { mkdirSync,readFileSync,writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import * as q from './qa94-support.mjs';
const { chromium }=await import(process.env.QA_PLAYWRIGHT_MODULE||'playwright');
const out=resolve(process.env.QA_OUTPUT_DIR||'output/qa/finite94/run');mkdirSync(out,{recursive:true});
const head=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();if(process.env.QA_EXPECTED_HEAD)assert.equal(head,process.env.QA_EXPECTED_HEAD);
const paths=[...q.sources,'scripts/qa94-finite.mjs','scripts/qa94-support.mjs','test/browser/worker-harness.mjs'];const hashes=()=>Object.fromEntries(paths.map(p=>[p,q.sha(readFileSync(p))]));
export const required={
 '94-CART-READ':['old-success','old-real-404','normal-retry'],
 '94-CHECKOUT-READ':['old-success-new-direct-intent','old-real-404-new-direct-intent','normal-current-checkout'],
 '94-CHECKOUT-SUBMIT':['real-201-receipt-cart-snapshot','real-409-leave-no-replay','explicit-retry-201'],
 '94-LOCALORDERS-TIMEOUT':['native-12s-abort-cached-feedback','cancelled-transport-no-delivery','explicit-retry-matching-status'],
 '94-LOCALORDERS-CANCEL':['native-leave-cancel','fresh-return-status','old-cancelled-no-overwrite','explicit-retry'],
 '94-IMAGE-PRIMARY-ORDER':['second-before-first','old-reader-error','explicit-save-byte-proof'],
 '94-IMAGE-GALLERY-ORDER':['busy-selection-rejected','new-read-old-finally','explicit-save-byte-order'],
 '94-PROFILE-RETURN':['native-back-exact-unsaved-draft','only-explicit-save'],
 '94-ADDRESS-RETURN':['native-back-dialog-focus-cleanup','only-explicit-save'],
 '94-VARIANT-RETURN':['old-second-variant-delivery','normal-variant-controls'],
 '94-IMAGE-DIALOG-RETURN':['old-image-navigation-cleanup','normal-zoom-focus']};
const expected=Object.keys(required).flatMap(id=>[390,1280].map(width=>id+'@'+width));
const report={sourceHead:head,gitStatusBefore:execFileSync('git',['status','--porcelain'],{encoding:'utf8'}),sourceHashes:hashes(),startedAt:new Date().toISOString(),scope:'22 non-PWA rows of fixed24 engineering verification matrix; English, cached Chromium, disposable real Worker/API/SQLite. Profile same-document nativeBack exact draft assertion; successful orders preserve receipt navigation. No change to user acceptance scope.',expectedRows:expected,complete24:false,cases:[],pageErrors:[],externalRequests:[],dialogs:[],cleanup:[]};
let browser,serial=0;
const business=r=>r.method!=='GET'&&!r.path.endsWith('/statuses')&&!r.path.endsWith('/session');
const noOrder=f=>assert.equal(f.requests.filter(r=>r.method==='POST'&&r.path==='/api/v1/orders').length,0);
const visibleFocus=async p=>assert.equal((await q.snap(p)).focus.visible,true);
const savedProfile='online-shopping-profile-v1',savedAddresses='online-shopping-addresses-v1';
const customerState=async p=>({view:await q.snap(p),cart:await q.cart(p),assignment:await p.locator('#assignment-list').innerText(),total:await p.locator('#checkout-total').innerText(),destination:await p.locator('#checkout-address').innerText(),back:await p.locator('#checkout-view .shop-actionbar a').getAttribute('href'),...(await p.evaluate(()=>location.hash==='#cart')?{cartSummary:await p.locator('#cart-total').innerText(),selected:await p.locator('#cart-selected-count').innerText()}:{})});
async function selectVariant(p,item){if(await p.locator('.variant-chooser-trigger').isVisible()){await p.locator('.variant-chooser-trigger').click();await p.locator('.variant-dialog[open] a[href="#product/'+item.id+'"]').click();}else await p.locator('.product-variant-options a[href="#product/'+item.id+'"]').click();}
async function run(id,width){if(process.env.QA_CASE_FILTER&&!new RegExp(process.env.QA_CASE_FILTER).test(id))return;
 const c={id,width,status:'UNVERIFIED',requiredSubsteps:required[id],substeps:required[id].map(name=>({name,status:'UNVERIFIED'})),expectation:'All fixed required substeps must pass; omission cannot close row'};let f,p;const errors=report.pageErrors.length;
 async function step(name,fn){const s=c.substeps.find(s=>s.name===name);assert.ok(s);try{s.evidence=await fn();s.status='PASS';}catch(e){s.status='FAIL';s.error=q.safe(e.stack||e.message,f?.secrets||[]);}finally{if(p&&!p.isClosed()){s.current=await q.snap(p).catch(()=>null);s.screenshot=`${++serial}-${id}-${width}-${name}-${s.status}.png`;await p.screenshot({path:out+'/'+s.screenshot,fullPage:true}).catch(e=>s.screenshotError=e.message);}console.log(s.status+' '+width+' '+id+'/'+name);}}
 try{f=await q.start(browser,width,report,id);c.fixture={A:{id:f.A.id,sku:f.A.sku,priceMinor:1290,currency:'MYR'},B:{id:f.B.id,sku:f.B.sku,priceMinor:1790,currency:'MYR'},production:false,credentialsSerialized:false};c.domainBefore=f.domain();
 if(id==='94-CART-READ'){
  for(const error of [false,true])await step(error?'old-real-404':'old-success',async()=>{p=await q.customer(f);await q.add(f,p,f.A);await q.route(p,'cart');await q.cartReady(p);if(error)f.A=await f.api('PATCH','/api/v1/seller/products/'+f.A.id,{active:false});const d=q.hold(f,'GET','/api/v1/products/'+f.A.id);await q.route(p,'product/'+f.B.id);await q.customerReady(p,f.B);await q.route(p,'cart');await q.poll(()=>d.release);await q.route(p,'product/'+f.B.id);await q.customerReady(p,f.B);if(error)f.A=await f.api('PATCH','/api/v1/seller/products/'+f.A.id,{active:true});await p.goBack();await q.cartReady(p);await p.locator('#checkout-button').focus();const before=await customerState(p),domain=f.domain();const delivered=await q.release(f,d);assert.equal(delivered.browserStatus,error?404:200);assert.deepEqual(await customerState(p),before);assert.deepEqual(f.domain(),domain);noOrder(f);await visibleFocus(p);return{delivered,before,after:await customerState(p),domainUnchanged:true};});
  await step('normal-retry',async()=>{await q.route(p,'product/'+f.B.id);await q.customerReady(p,f.B);await q.route(p,'cart');await q.cartReady(p);assert.equal(await p.locator('#cart-retry').isVisible(),false);noOrder(f);return{currentCart:await q.cart(p),enabledCheckout:true};});
 }
 if(id==='94-CHECKOUT-READ'){
  for(const error of [false,true])await step(error?'old-real-404-new-direct-intent':'old-success-new-direct-intent',async()=>{p=await q.customer(f);await q.profileAddress(f,p);await q.add(f,p,f.A);await q.route(p,'cart');await q.cartReady(p);if(error)f.A=await f.api('PATCH','/api/v1/seller/products/'+f.A.id,{active:false});const d=q.hold(f,'GET','/api/v1/products/'+f.A.id);await q.route(p,'checkout');await q.poll(()=>d.release);await q.route(p,'product/'+f.B.id);await q.customerReady(p,f.B);if(error)f.A=await f.api('PATCH','/api/v1/seller/products/'+f.A.id,{active:true});await p.locator('.product-buy').click();await p.waitForFunction(()=>location.hash==='#checkout'&&!document.querySelector('#submit-order').disabled);assert.match(await q.assignment(p),/Fictional BETA/);await p.locator('#change-address').focus();const before=await customerState(p),domain=f.domain();const delivered=await q.release(f,d);assert.equal(delivered.browserStatus,error?404:200);assert.deepEqual(await customerState(p),before,'Old cart read cannot own newer direct B checkout or redirect it');assert.deepEqual(f.domain(),domain);noOrder(f);return{oldIntent:{kind:'cart',productId:f.A.id},currentIntent:{kind:'direct',productId:f.B.id},delivered,before,after:await customerState(p)};});
  await step('normal-current-checkout',async()=>{await q.route(p,'product/'+f.B.id);await q.customerReady(p,f.B);await p.locator('.product-buy').click();await p.waitForFunction(()=>location.hash==='#checkout'&&!document.querySelector('#submit-order').disabled);assert.match(await q.assignment(p),/Fictional BETA/);assert.equal(await p.locator('#checkout-view .shop-actionbar a').getAttribute('href'),'#product/'+f.B.id);assert.match(await p.locator('#checkout-total').innerText(),/17\.90/);noOrder(f);return{currentIntent:await customerState(p)};});
 }
 if(id==='94-CHECKOUT-SUBMIT'){
  await step('real-201-receipt-cart-snapshot',async()=>{p=await q.customer(f);await q.checkout(f,p);const d=q.hold(f,'POST','/api/v1/orders');await p.locator('#submit-order').click();await q.poll(()=>d.release);assert.equal(d.record.status,201);assert.equal(await p.locator('#checkout-status').innerText(),'Submitting order…');assert.equal(await p.locator('#submit-order').isDisabled(),true);assert.equal(f.orders().length,1);const items=f.orderItems(),orders=f.orders();assert.deepEqual(items.map(x=>({q:x.quantity,p:x.price_minor,c:x.currency})),[{q:2,p:1290,c:'MYR'}]);await q.add(f,p,f.A,1);assert.equal((await q.cart(p))[0].quantity,3);f.A=await f.api('PATCH','/api/v1/seller/products/'+f.A.id,{priceMinor:1490});const delivered=await q.release(f,d);await p.waitForFunction(()=>location.hash==='#receipt');assert.deepEqual(f.orderItems(),items);assert.deepEqual(f.orders(),orders);assert.equal((await q.cart(p))[0].quantity,1);const local=await q.localOrders(p);assert.equal(local.length,1);assert.equal(local[0].totalMinor,2580);assert.equal(local[0].currency,'MYR');assert.equal(f.requests.filter(r=>r.method==='POST'&&r.path==='/api/v1/orders').length,1);return{commitBeforeDelivery:true,delivered,originalItems:items,orders,localReceipt:local,cartAfter:await q.cart(p),successRoute:'#receipt'};});
  let rejected;
  await step('real-409-leave-no-replay',async()=>{f.A=await f.api('PATCH','/api/v1/seller/products/'+f.A.id,{priceMinor:1290});p=await q.customer(f);await q.checkout(f,p);f.A=await f.api('PATCH','/api/v1/seller/products/'+f.A.id,{priceMinor:1490});const d=q.hold(f,'POST','/api/v1/orders'),orders=f.orders();await p.locator('#submit-order').click();await q.poll(()=>d.release);assert.equal(d.record.status,409);assert.equal(await p.locator('#checkout-status').innerText(),'Submitting order…');assert.equal(await p.locator('#submit-order').isDisabled(),true);assert.deepEqual(f.orders(),orders);await q.route(p,'profile');await p.locator('#profile-form [name=fullName]').fill('Fictional unsaved rejection-return draft');await p.locator('#profile-form [name=fullName]').focus();const before=await q.snap(p);const delivered=await q.release(f,d);assert.deepEqual(await q.snap(p),before,'Old rejected checkout must not redirect or focus over current Profile draft');assert.deepEqual(f.orders(),orders);assert.equal(f.requests.filter(r=>r.method==='POST'&&r.path==='/api/v1/orders').length,2);rejected={orders,before,delivered};return rejected;});
  await step('explicit-retry-201',async()=>{await q.route(p,'cart');await q.cartReady(p);await p.locator('#checkout-button').click();await p.waitForFunction(()=>location.hash==='#checkout'&&!document.querySelector('#submit-order').disabled);assert.match(await p.locator('#checkout-total').innerText(),/29\.80/);const retryStep=c.substeps.find(s=>s.name==='explicit-retry-201');retryStep.preRetry={view:await q.snap(p),status:await p.locator('#checkout-status').innerText(),error:await p.locator('#checkout-error').innerText(),posts:f.requests.filter(r=>r.method==='POST'&&r.path==='/api/v1/orders').map(r=>({status:r.status,idempotencySha256:r.idempotencySha256})),orders:f.orders(),submitDisabled:await p.locator('#submit-order').isDisabled()};retryStep.preRetryScreenshot=`pre-retry-${width}-${id}.png`;await p.screenshot({path:out+'/'+retryStep.preRetryScreenshot,fullPage:true});assert.deepEqual(retryStep.preRetry.posts.map(r=>r.status),[201,409],'Return to Checkout must create no new request before explicit retry');assert.equal(retryStep.preRetry.orders.length,1);assert.equal(retryStep.preRetry.submitDisabled,false);assert.equal(retryStep.preRetry.error,'');assert.equal(retryStep.preRetry.status,'','Ready Checkout before explicit retry must not show stale Submitting order');const before=f.orders().length;await p.locator('#submit-order').click();await p.waitForFunction(()=>location.hash==='#receipt');assert.equal(f.orders().length,before+1);const posts=f.requests.filter(r=>r.method==='POST'&&r.path==='/api/v1/orders');assert.deepEqual(posts.map(r=>r.status),[201,409,201]);assert.equal(new Set(posts.map(r=>r.idempotencySha256)).size,3);assert.equal(f.orderItems().at(-1).price_minor,1490);assert.equal(f.orderItems().at(-1).currency,'MYR');return{onlyExplicitRetryCommitted:true,posts,orders:f.orders(),items:f.orderItems(),receiptRoute:'#receipt'};});
 }
 if(id.startsWith('94-LOCALORDERS-')){
  p=await q.customer(f);const key=randomUUID();f.secrets.add(key);const receipt=await f.api('POST','/api/v1/orders',{buyer:{fullName:'Fictional status buyer',whatsappPhone:'',email:'finite-buyer@example.invalid'},whatsappOrderContactOptIn:false,locale:'en',deliveries:[{recipient:{fullName:'Fictional recipient',phone:'+60123456789'},address:{line1:'1 Fictional test road',postcode:'50000',country:'MY'},items:[{productId:f.A.id,quantity:1,expectedPriceMinor:1290,expectedCurrency:'MYR'}]}]},{'idempotency-key':key});await p.evaluate(async({receipt,key,A})=>{const s=await(await import('/shop/local-orders.js')).createLocalOrderStore();await s.save(receipt,[{productId:A.id,name:A.name,quantity:1,unitPriceMinor:1290}],key);},{receipt,key,A:f.A});const fixtureStatus=status=>{const at=new Date(Date.now()+1000+(status==='REJECTED'?1000:0)).toISOString();f.app.database.run('UPDATE shop_order SET status=?,updated_at=? WHERE order_no=?',status,at,receipt.orderNo);f.fixtureChanges.push({method:'LOCAL_SQL_FIXTURE',table:'shop_order',orderNo:receipt.orderNo,status,updatedAt:at,notSellerUIProof:true});};fixtureStatus('CONFIRMED');const d=q.hold(f,'POST','/api/v1/orders/statuses');await q.route(p,'orders');await q.poll(()=>d.release);const before=await q.localOrders(p),domain=f.domain();assert.equal(before[0].status,'SUBMITTED');
  if(id.endsWith('TIMEOUT')){
   await step('native-12s-abort-cached-feedback',async()=>{const start=Date.now();await p.waitForFunction(()=>!document.querySelector('#refresh-order-statuses').disabled&&document.querySelector('#local-orders-sync-status').textContent.includes('outdated'),{},{timeout:14500});assert.deepEqual(await q.localOrders(p),before);const fetch=await p.evaluate(()=>__qaFetch.filter(x=>x.path==='/api/v1/orders/statuses'));assert.equal(fetch.at(-1).error,'AbortError');assert.ok(Date.now()-start>=10500);assert.deepEqual(f.domain(),domain);return{nativeTimeoutMilliseconds:12000,clockInjection:false,elapsedMs:Date.now()-start,fetch,cached:before,feedback:await p.locator('#local-orders-sync-status').innerText()};});
   await step('cancelled-transport-no-delivery',async()=>{const delivered=await q.release(f,d);assert.ok(delivered.transport.includes('cancelled'));assert.deepEqual(await q.localOrders(p),before);return delivered;});
   await step('explicit-retry-matching-status',async()=>{await p.locator('#refresh-order-statuses').click();await p.waitForFunction(()=>document.querySelector('#local-orders-sync-status').textContent.includes('Seller statuses refreshed.'));const current=await q.localOrders(p);assert.equal(current.length,1);assert.equal(current[0].orderNo,receipt.orderNo);assert.equal(current[0].status,'CONFIRMED');assert.deepEqual(f.domain(),domain);noOrder(f);return{matchingOnly:current,requests:f.requests.filter(r=>r.path.endsWith('/statuses'))};});
  }else{
   await step('native-leave-cancel',async()=>{await q.route(p,'product/'+f.B.id);await q.customerReady(p,f.B);await q.poll(()=>d.failure);assert.deepEqual(await q.localOrders(p),before);return{failure:d.failure,nativeFetch:await p.evaluate(()=>__qaFetch.filter(x=>x.path.endsWith('/statuses')))};});
   await step('fresh-return-status',async()=>{fixtureStatus('REJECTED');await p.goBack();await p.waitForFunction(()=>location.hash==='#orders'&&document.querySelector('#local-orders-sync-status').textContent.includes('Seller statuses refreshed.'));assert.equal((await q.localOrders(p))[0].status,'REJECTED');return{current:await q.localOrders(p)};});
   await step('old-cancelled-no-overwrite',async()=>{await p.locator('#refresh-order-statuses').focus();const current={view:await q.snap(p),orders:await q.localOrders(p)},now=f.domain();const delivered=await q.release(f,d);assert.ok(delivered.transport.includes('cancelled'));assert.deepEqual({view:await q.snap(p),orders:await q.localOrders(p)},current);assert.deepEqual(f.domain(),now);return{delivered,current};});
   await step('explicit-retry',async()=>{await p.locator('#refresh-order-statuses').click();await p.waitForFunction(()=>document.querySelector('#local-orders-sync-status').textContent.includes('Seller statuses refreshed.')&&!document.querySelector('#refresh-order-statuses').disabled);assert.equal((await q.localOrders(p))[0].status,'REJECTED');noOrder(f);return{orders:await q.localOrders(p)};});
  }
 }
 if(id==='94-IMAGE-PRIMARY-ORDER'){
  p=await q.seller(f);await q.holdReads(p);const orders=f.orders();
  await step('second-before-first',async()=>{await p.locator('[name=image]').setInputFiles(q.files[2]);await q.waitReads(p,1);await p.locator('[name=image]').setInputFiles(q.files[3]);await q.waitReads(p,2);await q.deliverRead(p,1);const before=await q.imageBytes(p);assert.equal(before.primary.sha256,q.sha(q.files[3].buffer));await q.deliverRead(p,0);assert.deepEqual(await q.imageBytes(p),before);return{instrumentation:'Native FileReader reads complete, actual onload delivery held/reordered',fileHashes:q.files.slice(2).map(x=>({name:x.name,sha256:q.sha(x.buffer)})),draft:before};});
  await step('old-reader-error',async()=>{await p.locator('[name=image]').setInputFiles(q.files[2]);await q.waitReads(p,3);await p.locator('[name=image]').setInputFiles(q.files[1]);await q.waitReads(p,4);await q.deliverRead(p,3);const before=await q.imageBytes(p);await q.deliverRead(p,2,true);assert.deepEqual(await q.imageBytes(p),before);assert.equal(before.primary.sha256,q.sha(q.files[1].buffer));assert.equal(await p.locator('#product-form-error').innerText(),'');return{instrumentation:'Explicit injected old FileReader onerror after newer native read onload',draft:before};});
  await step('explicit-save-byte-proof',async()=>{const result=await q.explicitSave(f,p);assert.equal(result.images.primary.sha256,q.sha(q.files[1].buffer));assert.equal(q.sha(f.app.database.get('SELECT image_data FROM product WHERE id=?',f.A.id).image_data),q.sha(q.files[1].buffer));assert.deepEqual(f.orders(),orders);assert.equal(f.app.database.get('SELECT price_minor,currency FROM product WHERE id=?',f.A.id).price_minor,1290);return{...result,sqlitePrimarySha256:q.sha(q.files[1].buffer),ordersUnchanged:true};});
 }
 if(id==='94-IMAGE-GALLERY-ORDER'){
  p=await q.seller(f);await q.holdReads(p);const orders=f.orders();
  await step('busy-selection-rejected',async()=>{await p.locator('[name=gallery]').setInputFiles(q.files[2]);await q.waitReads(p,1);assert.equal(await p.locator('[name=gallery]').isDisabled(),true);assert.equal(await p.locator('#product-save').isDisabled(),true);await p.locator('[name=gallery]').setInputFiles(q.files[3]);await q.tick(p);assert.equal(await p.evaluate(()=>__qaReads.length),1);await q.deliverRead(p,0);assert.deepEqual((await q.imageBytes(p)).gallery.map(x=>x.sha256),[q.sha(q.files[0].buffer),q.sha(q.files[2].buffer)]);return{injection:'Playwright setInputFiles on disabled gallery, adversarial duplicate change; not real user click',nativeReads:1,draft:await q.imageBytes(p)};});
  await step('new-read-old-finally',async()=>{await p.locator('[name=gallery]').setInputFiles(q.files[3]);await q.waitReads(p,2);await q.deliverRead(p,0);await q.deliverRead(p,0,true);assert.equal(await p.locator('#product-save').isDisabled(),true);assert.equal(await p.locator('[name=gallery]').isDisabled(),true);assert.equal(await p.locator('#product-form-error').innerText(),'');await q.deliverRead(p,1);assert.equal(await p.locator('#product-save').isDisabled(),false);assert.deepEqual((await q.imageBytes(p)).gallery.map(x=>x.sha256),[0,2,3].map(i=>q.sha(q.files[i].buffer)));return{injection:'Replay callbacks from an already-settled native reader while newer read pending; Promise does not re-execute old finally',claim:'Duplicate callbacks cannot release the new busy state; no independently delayed finally execution claimed',draft:await q.imageBytes(p)};});
  await step('explicit-save-byte-order',async()=>{const result=await q.explicitSave(f,p);assert.deepEqual(result.images.gallery.map(x=>x.sha256),[0,2,3].map(i=>q.sha(q.files[i].buffer)));const row=f.app.database.get('SELECT image_data,gallery_layout_json,price_minor,currency FROM product WHERE id=?',f.A.id),layout=JSON.parse(row.gallery_layout_json),gallery=f.app.database.all('SELECT id,data FROM product_gallery_image WHERE product_id=?',f.A.id);const map=Object.fromEntries(gallery.map(x=>[x.id,q.sha(x.data)]));const sqlite=layout.map(id=>id==='main'?q.sha(row.image_data):map[id]);assert.deepEqual(sqlite,[0,2,3].map(i=>q.sha(q.files[i].buffer)));assert.equal(row.price_minor,1290);assert.equal(row.currency,'MYR');assert.deepEqual(f.orders(),orders);return{...result,sqliteOrderedHashes:sqlite,ordersUnchanged:true};});
 }
 if(id==='94-PROFILE-RETURN'){
  p=await q.customer(f);
  await step('native-back-exact-unsaved-draft',async()=>{await q.route(p,'profile');for(const[k,v]of Object.entries({fullName:'Fictional unsaved Profile draft',phone:'123456789',email:'unsaved@example.invalid'}))await p.locator('#profile-form [name='+k+']').fill(v);const inputs=await p.locator('#profile-form input').evaluateAll(a=>a.map(x=>({name:x.name,value:x.value}))),storage=await q.stored(p,savedProfile),domain=f.domain();await p.locator('.account-sidebar a[href="#addresses"]').click();await p.goBack();await p.locator('#profile-view').waitFor({state:'visible'});assert.deepEqual(await p.locator('#profile-form input').evaluateAll(a=>a.map(x=>({name:x.name,value:x.value}))),inputs);assert.equal(await q.stored(p,savedProfile),storage);assert.deepEqual(f.domain(),domain);await visibleFocus(p);noOrder(f);return{sameDocumentNativeBack:true,reloadCloseExcluded:true,draft:inputs,storageBefore:storage,storageAfter:await q.stored(p,savedProfile)};});
  await step('only-explicit-save',async()=>{const before=await q.stored(p,savedProfile);await p.locator('#profile-form [type=submit]').click();await p.waitForFunction(()=>document.querySelector('#profile-status').textContent.includes('saved'));assert.notEqual(await q.stored(p,savedProfile),before);assert.equal(JSON.parse(await q.stored(p,savedProfile)).fullName,'Fictional unsaved Profile draft');assert.equal(f.requests.filter(business).length,0);return{explicitLocalSave:true,stored:JSON.parse(await q.stored(p,savedProfile))};});
 }
 if(id==='94-ADDRESS-RETURN'){
  p=await q.customer(f);
  await step('native-back-dialog-focus-cleanup',async()=>{await q.route(p,'addresses');const storage=await q.stored(p,savedAddresses),domain=f.domain();await p.locator('#add-address').click();await p.locator('.address-form [name=fullName]').fill('Fictional unsaved address draft');await q.route(p,'profile');await p.goBack();await p.locator('#addresses-view').waitFor({state:'visible'});assert.equal(await p.locator('dialog[open]').count(),0);assert.equal(await q.stored(p,savedAddresses),storage);assert.deepEqual(f.domain(),domain);await visibleFocus(p);return{nativeBack:true,dialogs:await p.locator('dialog[open]').count(),storageBefore:storage,storageAfter:await q.stored(p,savedAddresses)};});
  await step('only-explicit-save',async()=>{await p.locator('#add-address').click();const form=p.locator('.address-form');for(const[k,v]of Object.entries({fullName:'Fictional explicit recipient',phone:'123456789',line1:'2 Fictional test road',city:'Kuala Lumpur',postcode:'50000'}))await form.locator('[name='+k+']').fill(v);await form.locator('[name=region]').selectOption('W.P. Kuala Lumpur');await form.locator('[type=submit]').click();await p.locator('dialog[open]').waitFor({state:'hidden'});assert.equal(await p.locator('.address-card').count(),1);assert.equal(f.requests.filter(business).length,0);return{explicitLocalSave:true,stored:JSON.parse(await q.stored(p,savedAddresses))};});
 }
 if(id==='94-VARIANT-RETURN'){
  p=await q.customer(f);
  await step('old-second-variant-delivery',async()=>{const domain=f.domain(),storage=await q.cart(p),d=q.hold(f,'GET','/api/v1/products/'+f.B.id);await selectVariant(p,f.B);await q.poll(()=>d.release);await q.route(p,'settings');await p.goBack();await q.customerReady(p,f.B);await p.locator('#detail-quantity').fill('2');await p.locator('#detail-quantity').dispatchEvent('input');await p.locator('#detail-quantity').focus();const before=await q.snap(p),product=await p.locator('#product-view').innerText();const delivered=await q.release(f,d);assert.equal(delivered.browserStatus,200);assert.deepEqual(await q.snap(p),before);assert.equal(await p.locator('#product-view').innerText(),product);assert.match(product,/SYNTHETIC-BETA/);assert.match(product,/17\.90/);assert.deepEqual(await q.cart(p),storage);assert.deepEqual(f.domain(),domain);noOrder(f);return{delivered,current:before,product};});
  await step('normal-variant-controls',async()=>{await selectVariant(p,f.A);await q.customerReady(p,f.A);assert.equal(await p.locator('dialog[open]').count(),0);assert.equal(await p.locator('#detail-quantity').inputValue(),'2');noOrder(f);return{currentSku:f.A.sku,quantity:'2',normalChooser:true};});
 }
 if(id==='94-IMAGE-DIALOG-RETURN'){
  const d=q.hold(f,'GET','/api/v1/products/'+f.A.id+'/image');p=await q.customer(f);
  await step('old-image-navigation-cleanup',async()=>{await q.poll(()=>d.release);const domain=f.domain(),storage=await q.cart(p);await p.locator('.product-image-button').click();await p.locator('.image-viewer[open]').waitFor();await q.route(p,'product/'+f.B.id);await q.customerReady(p,f.B);await p.goBack();await q.customerReady(p,f.A);assert.equal(await p.locator('dialog[open]').count(),0);const delivered=await q.release(f,d);assert.equal(delivered.actualAPIStatus,200);await p.waitForFunction(()=>{const image=document.querySelector('.product-image-button img');return image.complete&&image.naturalWidth>0;});assert.equal(await p.locator('dialog[open]').count(),0);assert.equal(await p.evaluate(()=>location.hash),'#product/'+f.A.id);await visibleFocus(p);assert.deepEqual(await q.cart(p),storage);assert.deepEqual(f.domain(),domain);noOrder(f);return{actualImageResponse:delivered,delayedBytesSha256:q.sha(q.files[0].buffer),current:await q.snap(p),imageArrivalAllowed:true};});
  await step('normal-zoom-focus',async()=>{await p.locator('.product-image-button').click();await p.locator('.image-viewer[open]').waitFor();await p.keyboard.press('Escape');await p.locator('.image-viewer[open]').waitFor({state:'hidden'});await visibleFocus(p);assert.equal(await p.locator('.product-image-button').evaluate(x=>document.activeElement===x),true);noOrder(f);return{normalZoomEscape:true,focus:await q.snap(p)};});
 }
 assert.equal(report.pageErrors.length,errors);c.status=c.substeps.every(s=>s.status==='PASS')?'PASS':'FAIL';
 }catch(e){c.status='FAIL';c.setupOrInvariantError=q.safe(e.stack||e.message,f?.secrets||[]);}
 finally{if(f){c.requests=f.requests;c.fixtureChanges=f.fixtureChanges;c.domainAfter=f.domain();c.orders=f.orders();c.newPageErrors=report.pageErrors.slice(errors);c.nativeFetch=await Promise.all(f.pages.filter(p=>!p.isClosed()).map(p=>p.evaluate(()=>window.__qaFetch).catch(()=>null)));await f.close();Object.assign(c,q.safe(c,f.secrets));}report.cases.push(c);writeFileSync(out+'/results.json',JSON.stringify(report,null,2)+'\n');console.log(c.status+' ROW '+id+'@'+width);}
}
try{browser=await chromium.launch({headless:true});report.browser=browser.version();for(const width of[390,1280])for(const id of Object.keys(required))await run(id,width);}
catch(e){report.fatal=e.stack||e.message;process.exitCode=1;}
finally{if(browser)await browser.close();report.completedAt=new Date().toISOString();report.sourceHashesAfter=hashes();assert.deepEqual(report.sourceHashesAfter,report.sourceHashes);const actual=report.cases.map(c=>c.id+'@'+c.width);report.completeNonPWARowSet=actual.length===expected.length&&new Set(actual).size===expected.length&&expected.every(x=>actual.includes(x));report.summary={pass:report.cases.filter(c=>c.status==='PASS').length,fail:report.cases.filter(c=>c.status==='FAIL').length,unverifiedSteps:report.cases.flatMap(c=>c.substeps).filter(s=>s.status==='UNVERIFIED').length};writeFileSync(out+'/results.json',JSON.stringify(report,null,2)+'\n');if(report.summary.fail||report.fatal||(!process.env.QA_CASE_FILTER&&!report.completeNonPWARowSet))process.exitCode=1;console.log(JSON.stringify(report.summary));}
