import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { deflateSync } from 'node:zlib';
import { createApp } from '../src/server.js';
import { useWorkerIngress } from '../test/browser/worker-harness.mjs';

export const sha = (b) => createHash('sha256').update(b).digest('hex');
export const tick = (p) => p.evaluate(() => new Promise((r) => requestAnimationFrame(() => requestAnimationFrame(r))));
export async function poll(fn, label = 'expected local condition', ms = 6000) {const until = Date.now() + ms;while (Date.now() < until) {if (fn()) return;await new Promise((r) => setTimeout(r, 20));}throw Error('Timed out: ' + label);}
export async function bounded(operation, label, ms = 20000) {let timer;try {return await Promise.race([operation, new Promise((_, reject) => {timer = setTimeout(() => reject(Error('Bounded timeout: ' + label)), ms);})]);} finally {clearTimeout(timer);}}
function png(rgba) {const chunk = (name, data) => {const type = Buffer.from(name),body = Buffer.concat([type, data]);let crc = 0xffffffff;for (const byte of body) {crc ^= byte;for (let n = 0; n < 8; n++) crc = crc >>> 1 ^ (crc & 1 ? 0xedb88320 : 0);}const length = Buffer.alloc(4),check = Buffer.alloc(4);length.writeUInt32BE(data.length);check.writeUInt32BE((crc ^ 0xffffffff) >>> 0);return Buffer.concat([length, body, check]);};const header = Buffer.alloc(13);header.writeUInt32BE(16, 0);header.writeUInt32BE(16, 4);header[8] = 8;header[9] = 6;const row = Buffer.concat([Buffer.from([0]), ...Array.from({ length: 16 }, () => Buffer.from(rgba))]);return Buffer.concat([Buffer.from('89504e470d0a1a0a', 'hex'), chunk('IHDR', header), chunk('IDAT', deflateSync(Buffer.concat(Array(16).fill(row)))), chunk('IEND', Buffer.alloc(0))]);}
export const files = [[220, 40, 40, 255], [30, 70, 220, 255], [30, 170, 70, 255], [240, 190, 20, 255]].map((rgba, i) => ({ name: `fictional-${i}.png`, mimeType: 'image/png', buffer: png(rgba) }));
export const dataURL = (i) => 'data:image/png;base64,' + files[i].buffer.toString('base64');
export function safe(value, secrets) {if (typeof value === 'string') {for (const s of secrets) if (s) value = value.replaceAll(s, '[REDACTED]');return value;}if (Array.isArray(value)) return value.map((v) => safe(v, secrets));if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, /^(?:statusAccessKey|accessKey|csrfToken|password|token)$/i.test(k) ? { redacted: true, sha256: sha(String(v)) } : safe(v, secrets)]));return value;}
export const sources = execFileSync('git', ['ls-tree', '-r', '--name-only', 'HEAD', 'public', 'src'], { encoding: 'utf8' }).trim().split('\n').filter((p) => /\.(?:js|html|css|json|webmanifest)$/.test(p));
export async function start(browser, width, report, id) {
  const config = { dbPath: ':memory:', shopMode: 'manual', username: 'synthetic_finite94', password: randomUUID() + randomUUID(), production: false, publicOrigin: null };const secrets = new Set([config.password]);const app = await createApp(config),gateway = await useWorkerIngress(app, config);await new Promise((r) => app.server.listen(0, '127.0.0.1', r));const origin = 'http://127.0.0.1:' + app.server.address().port;
  const login = await fetch(origin + '/api/v1/seller/session', { method: 'POST', signal: AbortSignal.timeout(8000), headers: { origin, 'content-type': 'application/json' }, body: JSON.stringify({ username: config.username, password: config.password }) });assert.equal(login.status, 200);const cookie = login.headers.get('set-cookie').split(';')[0],csrf = (await login.json()).csrfToken;secrets.add(cookie);secrets.add(cookie.split('=')[1]);secrets.add(csrf);
  const f = { app, gateway, origin, config, secrets, contexts: [], pages: [], requests: [], fixtureChanges: [], id, width };
  f.api = async (method, path, body, headers = {}) => {const r = await fetch(origin + path, { method, signal: AbortSignal.timeout(8000), headers: { origin, cookie, 'x-csrf-token': csrf, ...(body ? { 'content-type': 'application/json' } : {}), ...headers }, ...(body ? { body: JSON.stringify(body) } : {}) });const result = await r.json();assert.ok(r.ok, 'Fictional fixture API ' + r.status);f.fixtureChanges.push({ method, path, status: r.status, body: safe(body, secrets) });return result;};
  await f.api('POST', '/api/v1/seller/setup', { mode: 'production', shopName: 'Fictional finite MVP verification' });await f.api('POST', '/api/v1/seller/categories', { code: 'FINITE_QA', label: 'Fictional finite category' });
  const product = (tag, i, price) => f.api('POST', '/api/v1/seller/products', { sku: 'SYNTHETIC-' + tag, name: 'Fictional ' + tag, description: 'Disposable finite ownership fixture', category: 'FINITE_QA', priceMinor: price, active: true, variantGroup: 'FINITE_VARIANT', variantLabel: tag, imageDataUrl: dataURL(i) });f.A = await product('ALPHA', 0, 1290);f.B = await product('BETA', 1, 1790);
  const tables = (await app.database.all("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT IN ('admin','session','rate_limit_attempt') ORDER BY name")).map((r) => r.name);f.domain = async () => Object.fromEntries(await Promise.all(await Promise.all(tables.map(async (t) => {assert.match(t, /^[a-z_]+$/);const rows = await app.database.all('SELECT * FROM ' + t + ' ORDER BY rowid');return [t, { rows: rows.length, sha256: sha(JSON.stringify(rows)) }];}))));
  f.orders = async () => await app.database.all('SELECT order_no,total_minor,currency,status FROM shop_order ORDER BY rowid');f.orderItems = async () => await app.database.all('SELECT product_id,sku_snapshot,name_snapshot,quantity,price_minor,currency FROM order_item ORDER BY rowid');
  f.context = async () => {const context = await browser.newContext({ viewport: { width, height: 900 }, serviceWorkers: 'block', reducedMotion: 'reduce' });f.contexts.push(context);await context.addInitScript(() => {const native = window.fetch;window.__qaFetch = [];window.fetch = async function (...args) {const input = args[0],url = new URL(typeof input === 'string' ? input : input.url, location.href);const event = { method: args[1]?.method || input.method || 'GET', path: url.pathname, query: url.search, started: Date.now() };window.__qaFetch.push(event);try {const result = await native.apply(this, args);event.status = result.status;event.settled = true;return result;} catch (error) {event.failed = true;event.error = error.name;throw error;}};});await context.route('**/*', (r) => {if (!r.request().url().startsWith(origin + '/')) {report.externalRequests.push({ id, width, scheme: new URL(r.request().url()).protocol });return r.abort();}return r.continue();});return context;};
  f.page = async () => {const context = await f.context(),page = await context.newPage();f.pages.push(page);page.setDefaultTimeout(8000);page.on('pageerror', (e) => report.pageErrors.push({ id, width, error: safe(e.message, secrets) }));page.on('dialog', async (d) => {report.dialogs.push({ id, width, type: d.type(), action: 'Accept only explicit discard of fictional fixture draft' });await d.accept();});page.on('request', (r) => {const url = new URL(r.url());const d = gateway.controls.responseDelays.find((d) => !d.nativeRequest && d.method === r.method() && d.path === url.pathname && Object.entries(d.query || {}).every(([k, v]) => url.searchParams.get(k) === v));if (d) {d.nativeRequest = r;d.page = page;}if (url.pathname.startsWith('/api/')) {const record = { method: r.method(), path: url.pathname, query: url.search };if (r.method() !== 'GET' && url.pathname !== '/api/v1/seller/session') {record.body = safe(r.postDataJSON(), secrets);const key = r.headers()['idempotency-key'];if (key) {secrets.add(key);record.idempotencySha256 = sha(key);}}f.requests.push(record);r.response().then((response) => record.status = response?.status() || null);}});page.on('requestfailed', (r) => {const d = gateway.controls.responseDelays.find((d) => d.nativeRequest === r);if (d) d.failure = r.failure()?.errorText;});return page;};
  f.close = async () => {for (const d of gateway.controls.responseDelays) d.release?.();for (const context of f.contexts) await context.close();await app.close();report.cleanup.push({ id, width, contextsClosed: f.contexts.length, serverClosed: true, inMemoryDatabaseClosed: true });};return f;
}
export const route = async (p, r) => {await p.evaluate((r) => location.hash = '#' + r, r);await p.waitForFunction((r) => location.hash === '#' + r, r);await tick(p);};
export const customerReady = async (p, item) => {await p.waitForFunction((sku) => document.querySelector('.product-key-details')?.textContent.includes(sku), item.sku);await p.waitForFunction(() => window.__qaFetch.filter((x) => x.path === '/api/v1/products' && new URLSearchParams(x.query).has('category')).at(-1)?.settled);await tick(p);};
export async function customer(f, item = f.A) {const p = await f.page();await p.goto(f.origin + '/shop/#product/' + item.id);await customerReady(p, item);return p;}
export async function seller(f) {const p = await f.page();await p.goto(f.origin + '/seller/#products/' + f.A.id);await p.locator('#login-view').waitFor({ state: 'visible' });await p.evaluate(({ username, password }) => {document.querySelector('#username').value = username;document.querySelector('#password').value = password;}, { username: f.config.username, password: f.config.password });await p.locator('#login-submit').click();await p.locator('#workspace').waitFor({ state: 'visible' });await p.waitForFunction((sku) => document.querySelector('[name=sku]')?.value === sku && !document.querySelector('#product-save').disabled, f.A.sku);await p.waitForLoadState('networkidle');return p;}
export const hold = (f, method, path, query = {}) => {const d = { method, path, query, started: false };f.gateway.controls.responseDelays.push(d);return d;};
export async function release(f, d) {await poll(() => d.release, 'real API response hold');assert.ok(d.nativeRequest);const index = await d.page.evaluate(({ method, path, query }) => window.__qaFetch.findIndex((e) => !e.settled && !e.failed && e.method === method && e.path === path && Object.entries(query).every(([k, v]) => new URLSearchParams(e.query).get(k) === v)), { method: d.method, path: d.path, query: d.query });d.release();const response = await bounded(d.nativeRequest.response(), 'native held response', 6000);await poll(() => d.released, 'server release');if (!response) {assert.ok(d.failure, 'Exact held native request cancelled');return { actualAPIStatus: d.record.status, transport: 'Exact native request cancelled; no client callback delivery claim', failure: d.failure };}assert.equal(response.status(), d.record.status);if (d.nativeRequest.resourceType() === 'image') {await bounded(response.finished(), 'native held image bytes', 6000);await tick(d.page);return { actualAPIStatus: d.record.status, browserStatus: response.status(), transport: 'Actual held native image response delivered', identityMatched: true };}assert.ok(index >= 0);await d.page.waitForFunction((i) => window.__qaFetch[i]?.settled, index);await tick(d.page);return { actualAPIStatus: d.record.status, browserStatus: response.status(), transport: 'Actual held native fetch delivered', identityMatched: true };}
export const snap = (p) => p.evaluate(() => ({ hash: location.hash, title: document.title, views: [...document.querySelectorAll('main section[id$="-view"]')].map((x) => ({ id: x.id, hidden: x.hidden })), fields: [...document.querySelectorAll('main input,main select,main textarea')].filter((x) => x.getClientRects().length).map((x) => ({ id: x.id, name: x.name, value: x.type === 'file' ? [...x.files].map((f) => f.name) : x.value, checked: x.checked })), status: [...document.querySelectorAll('main [role=status],main [role=alert]')].filter((x) => x.getClientRects().length).map((x) => x.textContent), dialogs: [...document.querySelectorAll('dialog')].map((x) => ({ open: x.open, label: x.getAttribute('aria-label') })), focus: { id: document.activeElement.id, tag: document.activeElement.tagName, name: document.activeElement.name || null, visible: document.activeElement === document.body || Boolean(document.activeElement.getClientRects().length) } }));
export const cart = (p) => p.evaluate(async () => {const s = await (await import('/shop/cart.js')).createCartStore();return s.list();});
export const localOrders = (p) => p.evaluate(async () => {const s = await (await import('/shop/local-orders.js')).createLocalOrderStore();return s.list().map(({ statusAccessKey, ...r }) => ({ ...r, hasSyntheticStatusKey: Boolean(statusAccessKey) }));});
export const stored = (p, key) => p.evaluate(async (key) => localStorage.getItem((await import('/shop/storage-scope.js')).storageKey(key)), key);
export async function add(f, p, item, quantity = 2) {await route(p, 'product/' + item.id);await customerReady(p, item);const before = (await cart(p)).find((x) => x.productId === item.id)?.quantity || 0;await p.locator('#detail-quantity').fill(String(quantity));await p.locator('#detail-quantity').dispatchEvent('input');await p.locator('.product-add').click();await p.waitForFunction(async ({ id, quantity }) => {const s = await (await import('/shop/cart.js')).createCartStore();return s.list().find((x) => x.productId === id)?.quantity === quantity;}, { id: item.id, quantity: before + quantity });}
export const cartReady = async (p) => {await p.locator('#cart-view').waitFor({ state: 'visible' });await p.waitForFunction(() => document.querySelectorAll('.cart-row').length > 0 && !document.querySelector('#checkout-button').disabled);await tick(p);};
export async function profileAddress(f, p) {await route(p, 'profile');await p.locator('#profile-form [name=fullName]').fill('Fictional local buyer');await p.locator('#profile-form [name=email]').fill('finite-buyer@example.invalid');await p.locator('#profile-form [type=submit]').click();await p.waitForFunction(() => document.querySelector('#profile-status').textContent.includes('saved'));await route(p, 'addresses');await p.locator('#add-address').click();const form = p.locator('.app-modal[open] .address-form');for (const [k, v] of Object.entries({ fullName: 'Fictional local recipient', phone: '123456789', line1: '1 Fictional test road', line2: '', city: 'Kuala Lumpur', postcode: '50000' })) await form.locator('[name=' + k + ']').fill(v);await form.locator('[name=region]').selectOption('W.P. Kuala Lumpur');await form.locator('[type=submit]').click();await p.locator('.app-modal[open]').waitFor({ state: 'hidden' });await p.locator('.address-card').waitFor();}
export async function checkout(f, p, item = f.A) {await profileAddress(f, p);await add(f, p, item, 2);await route(p, 'cart');await cartReady(p);await p.locator('#checkout-button').click();await p.locator('#checkout-view').waitFor({ state: 'visible' });await p.waitForFunction(() => document.querySelectorAll('.assignment-row').length === 1 && !document.querySelector('#submit-order').disabled);await tick(p);}
export const assignment = (p) => p.locator('#assignment-list').innerText();
export async function holdReads(p) {await p.evaluate(() => {window.__qaReads = [];const native = FileReader.prototype.readAsDataURL;window.__qaNativeRead = native;FileReader.prototype.readAsDataURL = function (file) {const callback = this.onload;this.onload = function (event) {const r = { name: file.name, bytes: file.size, nativeReadFinished: true, delivered: false, release: (fail = false) => {if (fail) this.onerror?.(new ProgressEvent('error'));else callback.call(this, event);r.delivered = true;} };__qaReads.push(r);};return native.call(this, file);};});}
export const waitReads = (p, n) => p.waitForFunction((n) => window.__qaReads?.length >= n, n);
export const deliverRead = async (p, index, fail = false) => {await p.evaluate(({ index, fail }) => __qaReads[index].release(fail), { index, fail });await tick(p);};
export const restoreReads = (p) => p.evaluate(() => {FileReader.prototype.readAsDataURL = window.__qaNativeRead;});
export async function imageBytes(p) {return p.evaluate(async () => {const hash = async (image) => {if (!image?.getAttribute('src')) return null;let bytes;if (image.src.startsWith('data:')) {const b = atob(image.src.split(',')[1]);bytes = Uint8Array.from(b, (c) => c.charCodeAt(0));} else {const r = await fetch(image.src);if (!r.ok) throw Error('Image API ' + r.status);bytes = new Uint8Array(await r.arrayBuffer());}const d = await crypto.subtle.digest('SHA-256', bytes);return { bytes: bytes.length, sha256: [...new Uint8Array(d)].map((b) => b.toString(16).padStart(2, '0')).join('') };};return { primary: await hash(document.querySelector('#product-image-preview')), gallery: await Promise.all([...document.querySelectorAll('.product-gallery-item img')].map(hash)) };});}
export async function explicitSave(f, p) {await restoreReads(p);const count = f.requests.filter((r) => r.method === 'PATCH' && r.path === '/api/v1/seller/products/' + f.A.id).length;await p.locator('#product-save').click();await p.waitForFunction(() => document.querySelector('#product-form-success')?.textContent === 'Product saved.');assert.equal(f.requests.filter((r) => r.method === 'PATCH' && r.path === '/api/v1/seller/products/' + f.A.id).length, count + 1);assert.equal(f.requests.filter((r) => r.method === 'PATCH' && r.path === '/api/v1/seller/products/' + f.A.id).at(-1).status, 200);return { status: 200, requests: 1, savedProductId: f.A.id, images: await imageBytes(p) };}
