import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { Readable } from 'node:stream';
import { mkdirSync,readFileSync,writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import * as q from './qa94-support.mjs';
import { installGitAssets } from './qa94-git-assets.mjs';
import { createApi } from '../src/app.js';
import { serveStatic } from '../src/static.js';
import worker from '../src/worker.js';
import { shopObjectName } from '../src/shop-setup.js';
import { errorResponse } from '../src/http.js';
const { chromium }=await import(process.env.QA_PLAYWRIGHT_MODULE||'playwright');
const out=resolve(process.env.QA_OUTPUT_DIR||'output/qa/finite94/pwa');mkdirSync(out,{recursive:true});
const head=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();if(process.env.QA_EXPECTED_HEAD)assert.equal(head,process.env.QA_EXPECTED_HEAD);
const predecessor=process.env.QA_PREDECESSOR_HEAD||'169165f4912b583d094d6a776daf41284abed6fc',target=process.env.QA_APPLICATION_TARGET_HEAD||head;
const bytes=(ref,path)=>execFileSync('git',['show',ref+':'+path],{maxBuffer:32*1024*1024});const version=(ref,s)=>/v\d+/.exec(bytes(ref,'public/'+s+'/version.js').toString())[0];
const old=version(predecessor,'seller'),next=version(target,'seller');assert.notEqual(old,next);for(const ref of[predecessor,target])for(const surface of['shop','seller'])assert.equal(/version:\s*'(v\d+)'/.exec(bytes(ref,`public/${surface}/sw.js`).toString())[1],version(ref,surface));
const paths=[...q.sources,'scripts/qa94-support.mjs','scripts/qa94-pwa.mjs','scripts/qa94-git-assets.mjs','test/browser/worker-harness.mjs'];const hashes=()=>Object.fromEntries(paths.map(p=>[p,q.sha(readFileSync(p))]));for(const path of q.sources)assert.equal(q.sha(readFileSync(path)),q.sha(bytes(target,path)),path+' target differs');
const steps=['primary-dirty-cancel','gallery-busy-no-activation','completion-no-auto-install-submit','explicit-save-genuine-update-target-save'];
const report={sourceHead:head,targetAssetSourceHead:target,predecessorHead:predecessor,versions:{predecessor:old,target:next},sourceHashes:hashes(),startedAt:new Date().toISOString(),scope:'Two fixed94-IMAGE-PWA rows. Native Chromium waiting/controller lifecycle; every static asset served from genuine committed Git bytes. Pending readers own loaded predecessor Seller version; target normal input/Save tested after genuine explicit update. No fake same-version upgrade.',expectedRows:['94-IMAGE-PWA@390','94-IMAGE-PWA@1280'],cases:[],pageErrors:[],externalRequests:[],dialogs:[],cleanup:[]};
const state=p=>p.evaluate(async()=>{const query=w=>w?new Promise(r=>{const c=new MessageChannel(),timer=setTimeout(()=>r('TIMEOUT'),3000);c.port1.onmessage=e=>{clearTimeout(timer);c.port1.close();r(e.data.version);};w.postMessage({type:'GET_VERSION'},[c.port2]);}):null;const reg=await navigator.serviceWorker.getRegistration('/seller/');return{scope:reg?.scope,controller:await query(navigator.serviceWorker.controller),waiting:await query(reg?.waiting),active:await query(reg?.active),caches:await caches.keys()};});

let browser,serial=0;
try{browser=await chromium.launch({headless:true});report.browser=browser.version();for(const width of[390,1280]){const c={id:'94-IMAGE-PWA',width,status:'UNVERIFIED',requiredSubsteps:steps,substeps:steps.map(name=>({name,status:'UNVERIFIED'})),loadedPendingReadOwner:{sourceHead:predecessor,sellerVersion:old},targetAfterReload:{sourceHead:target,sellerVersion:next},staticRequests:[]};let f,p;async function step(name,fn){const s=c.substeps.find(x=>x.name===name);try{s.evidence=await fn();s.status='PASS';}catch(e){s.status='FAIL';s.error=q.safe(e.stack||e.message,f?.secrets||[]);throw e;}finally{if(p&&!p.isClosed()){s.screenshot=`${++serial}-${width}-${name}-${s.status}.png`;await p.screenshot({path:out+'/'+s.screenshot,fullPage:true});}console.log(s.status+' '+width+' 94-IMAGE-PWA/'+name);}}
 try{f=await q.start(browser,width,report,c.id);const phase={head:predecessor};await installGitAssets(f,phase,c.staticRequests,browser,report);p=await q.seller(f);await p.waitForFunction(()=>Boolean(navigator.serviceWorker.controller));await p.reload();await p.locator('.product-gallery-item').first().waitFor();assert.equal((await state(p)).controller,old);assert.match(await p.locator('#seller-current-version').innerText(),new RegExp(old));await p.evaluate(()=>{window.__qaActivations=[];const native=ServiceWorker.prototype.postMessage;ServiceWorker.prototype.postMessage=function(data,...args){if(data?.type==='SKIP_WAITING')__qaActivations.push({type:data.type,at:Date.now()});return native.call(this,data,...args);};});await q.holdReads(p);const initial=f.domain();
 await step('primary-dirty-cancel',async()=>{await p.locator('[name=image]').setInputFiles(q.files[2]);await q.waitReads(p,1);phase.head=target;await p.locator('#account-button').click();await p.locator('#check-updates-button').click();await p.locator('#account-button').click();await p.waitForFunction(v=>document.querySelector('#install-update-button').textContent.includes(v),next);assert.equal((await state(p)).waiting,next);await p.locator('#install-update-button').click();await p.locator('.app-modal-confirm[open]').waitFor();const draft=await q.snap(p);await p.keyboard.press('Escape');await p.locator('.app-modal-confirm').waitFor({state:'detached'});assert.equal((await state(p)).controller,old);assert.equal(await p.locator('[name=image]').evaluate(x=>x.files[0].name),q.files[2].name);assert.equal(await p.evaluate(()=>__qaReads[0].delivered),false);assert.equal(await p.evaluate(()=>__qaActivations.length),0);assert.deepEqual(f.domain(),initial);return{state:await state(p),pendingReadOwner:c.loadedPendingReadOwner,draft,actualConfirmationCancel:true};});
 await q.deliverRead(p,0);assert.equal((await q.imageBytes(p)).primary.sha256,q.sha(q.files[2].buffer));assert.equal((await state(p)).controller,old);assert.equal(f.requests.filter(r=>r.method==='PATCH').length,0);await q.explicitSave(f,p);await q.holdReads(p);
 await step('gallery-busy-no-activation',async()=>{await p.locator('[name=gallery]').setInputFiles(q.files[3]);await q.waitReads(p,1);assert.equal(await p.locator('#product-save').isDisabled(),true);const installDisabled=await p.locator('#install-update-button').isDisabled();if(installDisabled)await p.locator('#install-update-button').evaluate(x=>x.dispatchEvent(new MouseEvent('click',{bubbles:true})));else await p.locator('#install-update-button').click();await q.tick(p);assert.equal(await p.locator('.app-modal-confirm').count(),0);assert.equal(await p.evaluate(()=>__qaActivations.length),0);assert.equal((await state(p)).controller,old);return{interaction:installDisabled?'Explicit injected click on disabled Install button':'Actual trusted Install click rejected by existing busy guard',installDisabled,state:await state(p),pendingReadOwner:c.loadedPendingReadOwner};});
 await step('completion-no-auto-install-submit',async()=>{const writes=f.requests.filter(r=>r.method==='PATCH').length;await q.deliverRead(p,0);const images=await q.imageBytes(p);assert.deepEqual(images.gallery.map(x=>x.sha256),[2,3].map(i=>q.sha(q.files[i].buffer)));assert.equal(f.requests.filter(r=>r.method==='PATCH').length,writes);assert.equal(f.requests.filter(r=>r.method==='POST'&&r.path==='/api/v1/orders').length,0);assert.equal(await p.evaluate(()=>__qaActivations.length),0);assert.equal((await state(p)).controller,old);assert.equal((await state(p)).waiting,next);assert.equal(await p.locator('#install-update-button').isDisabled(),false);return{draftImages:images,state:await state(p),autoInstalls:0,autoSaves:0,autoOrders:0};});
 await step('explicit-save-genuine-update-target-save',async()=>{const saved=await q.explicitSave(f,p);await p.locator('#install-update-button').click();await p.waitForFunction(v=>document.querySelector('#seller-current-version')?.textContent.includes(v),next);await p.locator('.product-gallery-item').first().waitFor();assert.equal((await state(p)).controller,next);assert.equal((await state(p)).waiting,null);const installed=await state(p);const cache=await p.evaluate(async version=>{const c=await caches.open('os-seller-'+version),r=await c.match('/seller/app.js');return r?Array.from(new Uint8Array(await r.arrayBuffer())):null;},next);assert.ok(cache);assert.equal(q.sha(Buffer.from(cache)),q.sha(bytes(target,'public/seller/app.js')));assert.deepEqual((await q.imageBytes(p)).gallery.map(x=>x.sha256),[2,3].map(i=>q.sha(q.files[i].buffer)));await q.holdReads(p);await p.locator('[name=image]').setInputFiles(q.files[1]);await q.waitReads(p,1);await q.deliverRead(p,0);const targetSaved=await q.explicitSave(f,p);assert.equal(targetSaved.images.primary.sha256,q.sha(q.files[1].buffer));assert.equal(q.sha(f.app.database.get('SELECT image_data FROM product WHERE id=?',f.A.id).image_data),q.sha(q.files[1].buffer));assert.equal(f.requests.filter(r=>r.method==='PATCH').length,3);assert.equal(f.orders().length,0);return{saved,installed,genuineCachedAppSha256:q.sha(Buffer.from(cache)),targetSaved,targetLoadedInputOwner:{sourceHead:target,sellerVersion:next},actualExplicitSaves:3};});c.status=c.substeps.every(s=>s.status==='PASS')?'PASS':'FAIL';
 }catch(e){c.status='FAIL';c.error=q.safe(e.stack||e.message,f?.secrets||[]);}finally{if(f){c.requests=f.requests;c.orders=f.orders();c.domainAfter=f.domain();await f.close();Object.assign(c,q.safe(c,f.secrets));}report.cases.push(c);writeFileSync(out+'/results.json',JSON.stringify(report,null,2)+'\n');console.log(c.status+' ROW 94-IMAGE-PWA@'+width);}}
}catch(e){report.fatal=e.stack||e.message;}
finally{if(browser)await browser.close();report.completedAt=new Date().toISOString();report.sourceHashesAfter=hashes();assert.deepEqual(report.sourceHashesAfter,report.sourceHashes);report.completeRowSet=report.cases.length===2&&report.expectedRows.every(x=>report.cases.some(c=>c.id+'@'+c.width===x));report.summary={pass:report.cases.filter(c=>c.status==='PASS').length,fail:report.cases.filter(c=>c.status==='FAIL').length};writeFileSync(out+'/results.json',JSON.stringify(report,null,2)+'\n');if(report.fatal||report.summary.fail||!report.completeRowSet)process.exitCode=1;}
