import { randomBytes } from 'node:crypto';
import { ApiError } from '../http.js';
import { boundedText, FieldError } from '../validation.js';
import { resetPasswordFromHost } from '../accounts.js';
import { normalizeTenantCode } from './tenant-code.js';
import { createTenant } from './provisioner.js';
import { recordAudit } from './platform-db.js';

const fields = 'id, code, name, status, currency, is_default, seller_username, revision, delete_after, created_at, updated_at';
export const shopView = (row) => ({ id: row.id, code: row.code, name: row.name, status: row.status, currency: row.currency,
  isDefault: row.is_default === 1, sellerUsername: row.seller_username, revision: row.revision, deleteAfter: row.delete_after,
  createdAt: row.created_at, updatedAt: row.updated_at });
const unknown = () => new ApiError(404, 'NOT_FOUND', 'Not found.');
const conflict = () => new ApiError(409, 'STATE_CONFLICT', 'The shop changed. Refresh and try again.');
export function createShopManagement({ platform, pool, deps, registry, defaultStore, publicOrigin, sellerOrigin, clock = Date.now }) {
  const stamp = () => new Date(clock()).toISOString();
  async function rowFor(id) {
    if (typeof id !== 'string' || !/^[0-9a-f-]{36}$/.test(id)) throw unknown();
    const row = await platform.get('SELECT * FROM tenant WHERE id = ?', id);
    if (!row) throw unknown();
    return row;
  }
  return {
    async list() { return { items: (await platform.all(`SELECT ${fields} FROM tenant WHERE status <> 'PURGED' ORDER BY created_at, id LIMIT 20`)).map(shopView) }; },
    async detail(id) {
      const row = await rowFor(id);
      const result = shopView(row);
      if (['ACTIVE', 'SUSPENDED', 'DELETING'].includes(row.status)) {
        const store = row.is_default === 1 ? defaultStore : await pool.get(row);
        result.orderCount = (await store.get('SELECT COUNT(*) AS n FROM shop_order')).n;
        result.productCount = (await store.get('SELECT COUNT(*) AS n FROM product')).n;
      }
      return result;
    },
    async create(input, actor) {
      if (Object.hasOwn(input, 'sellerPassword')) throw new FieldError('sellerPassword', 'The first password is generated by the platform.');
      const result = await createTenant(platform, deps, input, actor);
      registry.invalidate();
      return { tenant: shopView(await rowFor(result.tenant.id)), sellerPassword: result.sellerPassword,
        shopUrl: `${publicOrigin}/${result.tenant.code}/`, sellerUrl: `${sellerOrigin}/${result.tenant.code}/` };
    },
    async mutate(id, action, input, actor) {
      if (!Number.isSafeInteger(input.expectedRevision) || input.expectedRevision < 0) throw new FieldError('expectedRevision', 'Send the current shop revision.');
      const allowed = { suspend: [], resume: [], rename: ['code', 'name'], 'request-deletion': ['code'], 'cancel-deletion': [], 'reset-seller-password': [] };
      if (!Object.hasOwn(allowed, action)) throw unknown();
      if (Object.keys(input).some((key) => !['expectedRevision', ...allowed[action]].includes(key))) throw new FieldError('shop', 'Unexpected shop field.');
      const result = await platform.transaction(async () => {
        const row = await rowFor(id);
        if (row.is_default === 1) throw new ApiError(403, 'DEFAULT_SHOP', 'The default shop is managed on the host.');
        if (row.revision !== input.expectedRevision) throw conflict();
        let status = row.status, code = row.code, name = row.name, deleteAfter = row.delete_after, event, password;
        if (action === 'suspend') { if (status !== 'ACTIVE') throw conflict(); status = 'SUSPENDED'; event = 'TENANT_SUSPEND'; }
        if (action === 'resume') { if (status !== 'SUSPENDED') throw conflict(); status = 'ACTIVE'; event = 'TENANT_RESUME'; }
        if (action === 'rename') {
          if (!['ACTIVE', 'SUSPENDED'].includes(status)) throw conflict();
          code = input.code === undefined ? code : normalizeTenantCode(input.code);
          name = input.name === undefined ? name : boundedText(input.name, 'name', 80);
          if (code !== row.code) {
            if (await platform.get('SELECT 1 AS n FROM tenant WHERE code = ?', code) || await platform.get('SELECT 1 AS n FROM tenant_code_alias WHERE code = ?', code)) throw new ApiError(409, 'CODE_TAKEN', 'This shop code is already used.');
            await platform.run('INSERT INTO tenant_code_alias(code, tenant_id, created_at) VALUES (?, ?, ?)', row.code, row.id, stamp());
          }
          event = 'CODE_RENAME';
        }
        if (action === 'request-deletion') {
          if (status !== 'SUSPENDED') throw conflict();
          if (input.code !== code) throw new FieldError('code', 'Type the shop code exactly.');
          status = 'DELETING'; deleteAfter = new Date(clock() + 30 * 24 * 60 * 60_000).toISOString(); event = 'TENANT_DELETE_REQUESTED';
        }
        if (action === 'cancel-deletion') { if (status !== 'DELETING') throw conflict(); status = 'SUSPENDED'; deleteAfter = null; event = 'TENANT_DELETE_CANCELLED'; }
        if (action === 'reset-seller-password') {
          if (!['ACTIVE', 'SUSPENDED'].includes(status)) throw conflict();
          password = randomBytes(24).toString('base64url');
          await resetPasswordFromHost(await pool.get(row), row.seller_username, password);
          event = 'SELLER_PASSWORD_RESET';
        }
        await platform.run(`UPDATE tenant SET status = ?, code = ?, name = ?, delete_after = ?, revision = revision + 1, updated_at = ?
          WHERE id = ? AND status = ? AND revision = ?`, status, code, name, deleteAfter, stamp(), row.id, row.status, row.revision);
        await recordAudit(platform, { actor, action: event, tenantId: row.id, detail: code });
        return { tenant: shopView(await rowFor(row.id)), ...(password ? { sellerPassword: password } : {}) };
      });
      registry.invalidate();
      return result;
    },
    async audit(params) {
      const cursor = params.get('cursor'), requested = params.get('limit');
      const limit = requested === null ? 50 : Number(requested);
      if (!Number.isSafeInteger(limit) || limit < 1 || limit > 100) throw new FieldError('limit', 'Use 1 to 100.');
      let at = null, id = null;
      if (cursor) {
        [at, id] = cursor.split('|');
        if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(at || '') || !/^[0-9a-f-]{36}$/.test(id || '') || cursor.split('|').length !== 2) throw new FieldError('cursor', 'Invalid audit cursor.');
      }
      const rows = await platform.all(`SELECT id, actor, action, tenant_id, detail, created_at FROM platform_audit
        WHERE (? IS NULL OR created_at < ? OR (created_at = ? AND id < ?)) ORDER BY created_at DESC, id DESC LIMIT ?`, at, at, at, id, limit + 1);
      const more = rows.length > limit; if (more) rows.pop();
      const last = rows.at(-1);
      return { items: rows, nextCursor: more ? `${last.created_at}|${last.id}` : null };
    },
  };
}
